using System.Collections.Generic;

namespace Exacore.BLL.PdfBL
{
    public class DocFieldNames
    {

        public Dictionary<string, string> Fields { get; set; } = new Dictionary<string, string>();
        public Dictionary<int, string> JsaStepActions { get; set; } = new Dictionary<int, string>();
        public Dictionary<int, string> JsaCrewAttendance { get; set; } = new Dictionary<int, string>();

        public void SetGoodCatchFields()
        {
            Fields.Add("GOOD CATCH DATE", "Date");
            Fields.Add("GOOD CATCH TIME", "Time");
            Fields.Add("DEPARTMENT", "Department");
            Fields.Add("DIVISION", "Division");
            Fields.Add("AFFECTED JOBSITE LOCATION", "AffectedJobsiteLocation");
            Fields.Add("PROJECT NAME", "Project");
            Fields.Add("GOOD CATCH TYPE", "GoodCatchType");
            Fields.Add("SUPERVISOR", "Supervisor");
            Fields.Add("NAME  TITLE OF  GOOD CATCH IDENTIFIER", "Name");
            Fields.Add("GOOD CATCH DESCRIPTION", "Description");
            //Fields.Add("CONTROL METHOD", "ControlMethod");
            Fields.Add("undefined", "ControlMethod");
            Fields.Add("IMMEDIATE ACTION TAKEN", "ImmediateActionTaken");
            //Fields.Add("DATE", "");
            //Fields.Add("PREPARED BY", "ChangedBy");
        }

        public void SetIncidentAlertFields()
        {
            Fields.Add("PROJECT", "");
            Fields.Add("EQUIPMENT  INCIDENT LOCATION", "EquipmentIncidentLocation");
            Fields.Add("SUPERVISOR", "Supervisor");
            Fields.Add("INVOLVED JOB TITLE", "InvolvedJobTitle");
            //Fields.Add("PREPARED BY", "ChangedBy");
            //Fields.Add("DATE", "ChangedDate");
            Fields.Add("INCIDENT TIME", "Time");
            Fields.Add("INCIDENT Date", "Date");
            Fields.Add("PROJECT NAME", "Project");
            Fields.Add("Alert Type", "AlertTime");
            Fields.Add("Text1", "IncidentDescription");
            Fields.Add("Text2", "ImmediateActionTaken");
        }

        public void SetJsaFields()
        {
            Fields.Add("Text Field 100", "JobDescription");
            Fields.Add("Text Field 1012", "Page");
            Fields.Add("Text Field 1013", "Date");
            Fields.Add("Text Field 101", "JsaNo");
            Fields.Add("Text Field 102", "Rev");
            Fields.Add("Text Field 1016", "Reference");
            Fields.Add("Text Field 1017", "Title");
            Fields.Add("Text Field 1018", "Supervisor");
            Fields.Add("Text Field 1019", "AnalysisBy");
            Fields.Add("Text Field 1020", "ApprovedBy");
            Fields.Add("Text Field 1021", "Department");
            Fields.Add("Text Field 1022", "Location");
            //Fields.Add("Check Box 3", "");
            //Fields.Add("Check Box 4", "");

            JsaStepActions.Add(1, "12,11,10");
            JsaStepActions.Add(2, "13,14,15");
            JsaStepActions.Add(3, "16,20,21");
            JsaStepActions.Add(4, "17,18,19");
            JsaStepActions.Add(5, "22,26,30");
            JsaStepActions.Add(6, "24,27,31");
            JsaStepActions.Add(7, "23,28,32");
            JsaStepActions.Add(8, "36,39,43");
            JsaStepActions.Add(9, "35,40,44");
            JsaStepActions.Add(10, "37,41,45");
            JsaStepActions.Add(11, "46,50,54");
            JsaStepActions.Add(12, "48,51,55");
            JsaStepActions.Add(13, "47,52,56");
            JsaStepActions.Add(14, "49,53,57");
            JsaStepActions.Add(15, "58,62,66");
            JsaStepActions.Add(16, "60,63,67");

            JsaCrewAttendance.Add(1, "100,103");
            JsaCrewAttendance.Add(2, "104,105");
            JsaCrewAttendance.Add(3, "106,107");
            JsaCrewAttendance.Add(4, "108,109");
            JsaCrewAttendance.Add(5 , "1010,1011");


            #region JsaFields
            //Fields.Add("Text Field 12", "");
            //Fields.Add("Text Field 11", "");
            //Fields.Add("Text Field 22", "");
            //Fields.Add("Text Field 34", "");
            //Fields.Add("Text Field 46", "");
            //Fields.Add("Text Field 58", "");
            //Fields.Add("Text Field 16", "");
            //Fields.Add("Text Field 23", "");
            //Fields.Add("Text Field 35", "");
            //Fields.Add("Text Field 47", "");
            //Fields.Add("Text Field 13", "");
            //Fields.Add("Text Field 24", "");
            //Fields.Add("Text Field 36", "");
            //Fields.Add("Text Field 48", "");
            //Fields.Add("Text Field 60", "");
            //Fields.Add("Text Field 17", "");
            //Fields.Add("Text Field 25", "");
            //Fields.Add("Text Field 37", "");
            //Fields.Add("Text Field 49", "");
            //Fields.Add("Text Field 26", "");
            //Fields.Add("Text Field 38", "");
            //Fields.Add("Text Field 50", "");
            //Fields.Add("Text Field 62", "");
            //Fields.Add("Text Field 14", "");
            //Fields.Add("Text Field 27", "");
            //Fields.Add("Text Field 39", "");
            //Fields.Add("Text Field 51", "");
            //Fields.Add("Text Field 63", "");
            //Fields.Add("Text Field 20", "");
            //Fields.Add("Text Field 28", "");
            //Fields.Add("Text Field 40", "");
            //Fields.Add("Text Field 52", "");
            //Fields.Add("Text Field 18", "");
            //Fields.Add("Text Field 29", "");
            //Fields.Add("Text Field 41", "");
            //Fields.Add("Text Field 53", "");
            //Fields.Add("Text Field 10", "");
            //Fields.Add("Text Field 30", "");
            //Fields.Add("Text Field 42", "");
            //Fields.Add("Text Field 54", "");
            //Fields.Add("Text Field 66", "");
            //Fields.Add("Text Field 15", "");
            //Fields.Add("Text Field 31", "");
            //Fields.Add("Text Field 43", "");
            //Fields.Add("Text Field 55", "");
            //Fields.Add("Text Field 67", "");
            //Fields.Add("Text Field 21", "");
            //Fields.Add("Text Field 32", "");
            //Fields.Add("Text Field 44", "");
            //Fields.Add("Text Field 56", "");
            //Fields.Add("Text Field 19", "");
            //Fields.Add("Text Field 33", "");
            //Fields.Add("Text Field 45", "");
            //Fields.Add("Text Field 57", "");

            //Fields.Add("Check Box 3", "");
            //Fields.Add("Check Box 4", "");
            //Fields.Add("Text Field 70", "");
            //Fields.Add("Text Field 71", "");
            //Fields.Add("Text Field 72", "");
            //Fields.Add("Text Field 73", "");
            //Fields.Add("Text Field 74", "");
            //Fields.Add("Text Field 75", "");
            //Fields.Add("Text Field 76", "");
            //Fields.Add("Text Field 77", "");
            //Fields.Add("Text Field 104", "");
            //Fields.Add("Text Field 106", "");
            //Fields.Add("Text Field 108", "");
            //Fields.Add("Text Field 1010", "");
            //Fields.Add("Text Field 1023", "");
            //Fields.Add("Text Field 1024", "");
            //Fields.Add("Text Field 1026", "");
            //Fields.Add("Text Field 103", "");
            //Fields.Add("Text Field 105", "");
            //Fields.Add("Text Field 107", "");
            //Fields.Add("Text Field 109", "");
            //Fields.Add("Text Field 1011", "");
            //Fields.Add("Text Field 1015", "");
            //Fields.Add("Signature Field 11", "");
            //Fields.Add("Signature Field 2", "");
            //Fields.Add("Signature Field 3", "");
            //Fields.Add("Signature Field 5", "");
            //Fields.Add("Signature Field 7", "");
            //Fields.Add("Signature Field 9", "");
            //Fields.Add("Signature Field 1", "");
            //Fields.Add("Signature Field 4", "");
            //Fields.Add("Signature Field 6", "");
            //Fields.Add("Signature Field 8", "");
            //Fields.Add("Signature Field 10", "");
            //Fields.Add("Text Field 78", "");
            //Fields.Add("Text Field 79", "");
            //Fields.Add("Text Field 80", "");
            //Fields.Add("Text Field 81", "");
            //Fields.Add("Text Field 82", "");
            //Fields.Add("Text Field 83", "");
            //Fields.Add("Text Field 84", "");
            //Fields.Add("Text Field 85", "");
            //Fields.Add("Text Field 86", "");
            //Fields.Add("Text Field 87", "");
            //Fields.Add("Text Field 88", "");
            //Fields.Add("Text Field 89", "");
            //Fields.Add("Text Field 90", "");
            //Fields.Add("Text Field 91", "");
            //Fields.Add("Text Field 92", "");
            //Fields.Add("Text Field 93", "");
            //Fields.Add("Text Field 94", "");
            //Fields.Add("Text Field 95", "");
            //Fields.Add("Text Field 96", "");
            //Fields.Add("Text Field 97", "");
            //Fields.Add("Text Field 98", "");
            //Fields.Add("Text Field 99", "");
            #endregion
        }

        public void SetNearMissFields()
        {
            Fields.Add("DATE", "Date");
            Fields.Add("TIME", "Time");
            Fields.Add("DIVISION", "Division");
            Fields.Add("DEPARTMENT", "Department");
            Fields.Add("AFFECTED JOBSITE LOCATION", "AffectedJobsiteLocation");
            Fields.Add("PROJECT NAME", "Project");
            Fields.Add("NEAR MISS TYPE", "NearMissType");
            Fields.Add("SUPERVISOR", "Supervisor");
            Fields.Add("NAMETITLE OF REPORTING PERSON", "ReporingPerson");
            Fields.Add("SUPERVISOR_2", "");
            Fields.Add("SSHO", "Ssho");
            Fields.Add("PROJECTSITE MANAGER", "Manager");
            Fields.Add("Text1", "ImmediateAction");
            Fields.Add("Text2", "CorrectiveAction");
            Fields.Add("Text3", "NearMissDescription");
            Fields.Add("Text4", "ControlMethod");
            Fields.Add("Check Box4", "WrongselectionofPPE");
            Fields.Add("Check Box5", "DisregardSafetyRules");
            Fields.Add("Check Box6", "Employeefatigue");
            Fields.Add("Check Box7", "Failuretofollowprocedure");
            Fields.Add("Check Box8", "Takingshortcuts");
            Fields.Add("Check Box9", "Lackofattention");
            Fields.Add("Check Box10", "Workingtofast");
            Fields.Add("Check Box11", "Lackofemployeetraining");
            Fields.Add("Check Box12", "ImproperLiftingtechnique");
            Fields.Add("Check Box13", "Newtaskforemployeeorlackofexperience");
            Fields.Add("Check Box14", "Failuretosecureorwarn");
            Fields.Add("Check Box15", "Nooroutdatedprocedure");
            Fields.Add("Check Box16", "Operatingwithoutauthority");
            Fields.Add("Check Box17", "Hazardousmethodorprocedure");
            Fields.Add("Check Box18", "Poorpositioning");
            Fields.Add("Check Box19", "Unsafeposture");
            Fields.Add("Check Box20", "Travelingpublicenteringworkarea");
            Fields.Add("Check Box21", "IncompleteoroutdatedJSA");
            Fields.Add("Check Box22", "ImproperLOTO");
            Fields.Add("Check Box23", "Poororhousekeepingpractices");
            Fields.Add("Check Box24", "Guardremovedornotinstalledonequipment");
            Fields.Add("Check Box25", "Equipmentfailure");
            Fields.Add("Check Box26", "Impropermaterialorequipmentused");
            Fields.Add("Check Box27", "Weather");
            Fields.Add("Check Box28", "Other");

        }

        public void SetSiteSafetyOrientationFields()
        {
            Fields.Add("Text Field 1", "Date");
            Fields.Add("Text Field 2", "Name");
            Fields.Add("Text Field 3", "Project");
            Fields.Add("Text Field 4", "");
            Fields.Add("Text Field 5", "");
            Fields.Add("Text Field 7", "Date");
            Fields.Add("Text Field 6", "Name");
            Fields.Add("Text Field 9", "Date");
            Fields.Add("Signature Field 1", "");

            //Fields.Add("Check Box 1", "HouseKeeping");
            //Fields.Add("Check Box 2", "PowerTools");
            //Fields.Add("Check Box 3", "FirePrevention");
            //Fields.Add("Check Box 4", "Welding");
            //Fields.Add("Check Box 5", "ElectricalSafety");
            //Fields.Add("Check Box 6", "AerialLifts");
            //Fields.Add("Check Box 7", "Scaffolding");
            //Fields.Add("Check Box 8", "Trenching");
            //Fields.Add("Check Box 9", "FallProtection");
            //Fields.Add("Check Box 10", "FleetSafety");
            //Fields.Add("Check Box 11", "CraneSafety");
            Fields.Add("Check Box 12", "FirstAid");
            //Fields.Add("Check Box 13", "Pathogens");
            //Fields.Add("Check Box 14", "Lead");
            //Fields.Add("Check Box 15", "ConfinedSpaces");
            //Fields.Add("Check Box 16", "Lockout");
            //Fields.Add("Check Box 17", "ForkTrucks");
            //Fields.Add("Check Box 18", "ProtectiveEquipment");
            //Fields.Add("Check Box 19", "HearingProtection");
            //Fields.Add("Check Box 20", "DesignateFacilities");
            //Fields.Add("Check Box 21", "Coverage");
            //Fields.Add("Check Box 22", "ContactInformation");1
            Fields.Add("Check Box 23", "GeneralHealth");
            Fields.Add("Check Box 26", "FirePrevention");
            Fields.Add("Check Box 24", "HouseKeeping");
            Fields.Add("Check Box 27", "Welding");
            Fields.Add("Check Box 25", "PowerTools");
            Fields.Add("Check Box 28", "CompressedAir");
            Fields.Add("Check Box 29", "ElectricalSafety");
            Fields.Add("Check Box 30", "AerialLifts");
            Fields.Add("Check Box 31", "Scaffolding");
            Fields.Add("Check Box 32", "Trenching");
            Fields.Add("Check Box 33", "FallProtection");
            Fields.Add("Check Box 34", "FleetSafety");
            Fields.Add("Check Box 35", "CraneSafety"); //FirstAid
            Fields.Add("Check Box 36", "Pathogens");
            Fields.Add("Check Box 37", "Lead");
            Fields.Add("Check Box 38", "ConfinedSpaces");
            Fields.Add("Check Box 39", "Lockout");
            Fields.Add("Check Box 40", "ForkTrucks");
            Fields.Add("Check Box 41", "ProtectiveEquipment");
            Fields.Add("Check Box 42", "HearingProtection");
            Fields.Add("Check Box 43", "DesignateFacilities");
            Fields.Add("Check Box 44", "Coverage");
            Fields.Add("Check Box 45", "ContactInformation");

            //Fields.Add("Check Box 46", "WhatRequires");
            //Fields.Add("Check Box 47", "WhenToReport");
            //Fields.Add("Check Box 48", "Date");
            //Fields.Add("Check Box 49", "Date");
            //Fields.Add("Check Box 50", "Date");
            //Fields.Add("Check Box 51", "Date");
            //Fields.Add("Check Box 52", "Date");
            //Fields.Add("Check Box 53", "Date");
            //Fields.Add("Check Box 54", "Date");
            //Fields.Add("Check Box 55", "Date");
            //Fields.Add("Check Box 56", "Date");
            //Fields.Add("Check Box 57", "Date");
            //Fields.Add("Check Box 58", "Date");
            //Fields.Add("Check Box 59", "WhenToReport");
            //Fields.Add("Check Box 60", "Date");
            //Fields.Add("Check Box 61", "Date");
            //Fields.Add("Check Box 62", "Date");
            //Fields.Add("Check Box 63", "Date");
            //Fields.Add("Check Box 64", "Date");
            //Fields.Add("Check Box 65", "Date");
            //Fields.Add("Check Box 66", "Date");
            //Fields.Add("Check Box 67", "Date");
            //Fields.Add("Check Box 68", "Date");
            //Fields.Add("Check Box 69", "Date");
            Fields.Add("Check Box 70", "WhatRequires");
            Fields.Add("Check Box 71", "WhenToReport");
            Fields.Add("Check Box 72", "WhoToNotify");
            Fields.Add("Check Box 73", "TestingProcedures");
            Fields.Add("Check Box 74", "ReportingOfMedication");
            Fields.Add("Check Box 75", "Eap");
            Fields.Add("Check Box 76", "ProgressivePolicy");
            Fields.Add("Check Box 77", "ObtainInformation");
            Fields.Add("Check Box 78", "Sds");
            Fields.Add("Check Box 79", "HazardCommunication");
            Fields.Add("Check Box 80", "LabelingSystems");
            Fields.Add("Check Box 81", "ProtectiveMeasures");
            Fields.Add("Check Box 82", "AlarmSystems");
            Fields.Add("Check Box 83", "ShelterAreas");
            Fields.Add("Check Box 84", "MusteringZones");
            Fields.Add("Check Box 85", "AccountingProcedures");
            Fields.Add("Check Box 86", "HardHats");
            Fields.Add("Check Box 87", "SafetyVests");
            Fields.Add("Check Box 88", "HandProtection");
            Fields.Add("Check Box 89", "FootProtection");
            Fields.Add("Check Box 90", "FaceProtection");
            Fields.Add("Check Box 91", "HearingProtection2");
            Fields.Add("Check Box 92", "ProtectiveClothing");
            Fields.Add("Check Box 93", "PersonalFallArrest");
            //Fields.Add("Check Box 94", "StepLadders");
            //Fields.Add("Check Box 95", "Date");
            //Fields.Add("Check Box 96", "Date");
            //Fields.Add("Check Box 97", "Date");
            Fields.Add("Check Box 98", "StepLadders");
            Fields.Add("Check Box 99", "ExtensionLadders");
            Fields.Add("Check Box 100", "Capacities");
            Fields.Add("Check Box 101", "ProperUse");
        }

        public void SetToolboxMeetingFields()
        {
            Fields.Add("SUPERVISOR NAME", "Supervisor");
            Fields.Add("DATE", "Date");
            Fields.Add("JOB TITLE", "JobTitle");
            Fields.Add("EMPLOYEE ID NO", "EmployeeId");
            Fields.Add("PROJECT NAME", "Project");
            Fields.Add("PROJECT LOCATION", "Location");
            Fields.Add("PROJECT NOCONTRACT NO", "ProjectNo");
            Fields.Add("NO OF ATTENDEES", "NumberOfAttendees");
            Fields.Add("NO IN CREW", "CrewNo");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow1", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow2", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow3", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow4", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow5", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow6", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow7", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow8", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow9", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow10", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow11", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow12", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow13", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow14", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow15", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow16", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow17", "Date");
            //Fields.Add("TOPICS COVERED LISTBRIEF DESCRIPTIONRow18", "Date");
            //Fields.Add("SUPERVISOR SIGNATURE", "Date");
            //Fields.Add("NAME SIGNATURERow1", "Date");
            //Fields.Add("COMPANYRow1", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow1", "Date");
            //Fields.Add("NAME SIGNATURERow2", "Date");
            //Fields.Add("COMPANYRow2", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow2", "Date");
            //Fields.Add("NAME SIGNATURERow3", "Date");
            //Fields.Add("COMPANYRow3", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow3", "Date");
            //Fields.Add("NAME SIGNATURERow4", "Date");
            //Fields.Add("COMPANYRow4", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow4", "Date");
            //Fields.Add("NAME SIGNATURERow5", "Date");
            //Fields.Add("COMPANYRow5", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow5", "Date");
            //Fields.Add("NAME SIGNATURERow6", "Date");
            //Fields.Add("COMPANYRow6", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow6", "Date");
            //Fields.Add("NAME SIGNATURERow7", "Date");
            //Fields.Add("COMPANYRow7", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow7", "Date");
            //Fields.Add("NAME SIGNATURERow8", "Date");
            //Fields.Add("COMPANYRow8", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow8", "Date");
            //Fields.Add("NAME SIGNATURERow9", "Date");
            //Fields.Add("COMPANYRow9", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow9", "Date");
            //Fields.Add("NAME SIGNATURERow10", "Date");
            //Fields.Add("COMPANYRow10", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow10", "Date");
            //Fields.Add("NAME SIGNATURERow11", "Date");
            //Fields.Add("COMPANYRow11", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow11", "Date");
            //Fields.Add("NAME SIGNATURERow12", "Date");
            //Fields.Add("COMPANYRow12", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow12", "Date");
            //Fields.Add("NAME SIGNATURERow13", "Date");
            //Fields.Add("COMPANYRow13", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow13", "Date");
            //Fields.Add("NAME SIGNATURERow14", "Date");
            //Fields.Add("COMPANYRow14", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow14", "Date");
            //Fields.Add("NAME SIGNATURERow15", "Date");
            //Fields.Add("COMPANYRow15", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow15", "Date");
            //Fields.Add("NAME SIGNATURERow16", "Date");
            //Fields.Add("COMPANYRow16", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow16", "Date");
            //Fields.Add("NAME SIGNATURERow17", "Date");
            //Fields.Add("COMPANYRow17", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow17", "Date");
            //Fields.Add("NAME SIGNATURERow18", "Date");
            //Fields.Add("COMPANYRow18", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow18", "Date");
            //Fields.Add("NAME SIGNATURERow19", "Date");
            //Fields.Add("COMPANYRow19", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow19", "Date");
            //Fields.Add("NAME SIGNATURERow20", "Date");
            //Fields.Add("COMPANYRow20", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow20", "Date");
            //Fields.Add("NAME SIGNATURERow21", "Date");
            //Fields.Add("COMPANYRow21", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow21", "Date");
            //Fields.Add("NAME SIGNATURERow22", "Date");
            //Fields.Add("COMPANYRow22", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow22", "Date");
            //Fields.Add("NAME SIGNATURERow23", "Date");
            //Fields.Add("COMPANYRow23", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow23", "Date");
            //Fields.Add("NAME SIGNATURERow24", "Date");
            //Fields.Add("COMPANYRow24", "Date");
            //Fields.Add("COMMENTSSAFETY CONCERNS TRAINING REQUESTSRow24", "Date");
        }

        public void SetMotorizedEquipment()
        {
            Fields.Add("Text Field 1", "Date");
            Fields.Add("Text Field 2", "HourMeter");
            Fields.Add("Text Field 3", "Model");
            Fields.Add("Text Field 4", "InspectedBy");
            Fields.Add("Text Field 5", "OperationalInspection.Headlights");
            Fields.Add("Text Field 6", "OperationalInspection.ReverseLights");
            Fields.Add("Text Field 7", "OperationalInspection.RunningLights");
            Fields.Add("Text Field 8", "OperationalInspection.ParkingBrake");
            Fields.Add("Text Field 9", "OperationalInspection.BatteryGauge");
            Fields.Add("Text Field 10", "OperationalInspection.WaterLevelGauge");
            Fields.Add("Text Field 11", "OperationalInspection.TemperatureGauge");
            Fields.Add("Text Field 12", "OperationalInspection.TemperatureGauge");
            Fields.Add("Text Field 13", "OperationalInspection.OilLevelGauge");
            Fields.Add("Text Field 14", "OperationalInspection.FuelLevelGauge");
            Fields.Add("Text Field 15", "OperationalInspection.Horn");
            Fields.Add("Text Field 16", "OperationalInspection.ReverseSignal");
            Fields.Add("Text Field 17", "OperationalInspection.Brakes");
            Fields.Add("Text Field 18", "OperationalInspection.SeatBelt");
            Fields.Add("Text Field 19", "OperationalInspection.Chains");
            Fields.Add("Text Field 20", "OperationalInspection.HydraulicOutriggers");
            Fields.Add("Text Field 21", "OperationalInspection.HydraulicTilt");
            Fields.Add("Text Field 22", "OperationalInspection.HydraulicSideShift");
            Fields.Add("Text Field 23", "OperationalInspection.EngineOilLevel");
            Fields.Add("Text Field 24", "OperationalInspection.HydraulicOilLevel");
            Fields.Add("Text Field 25", "DamageInspection.SteeringControls");
            Fields.Add("Text Field 26", "DamageInspection.LeaksDetected");
            Fields.Add("Text Field 27", "DamageInspection.TiresAndWheels");
            Fields.Add("Text Field 28", "DamageInspection.Forks");
            Fields.Add("Text Field 29", "DamageInspection.Attachments");
            Fields.Add("Text Field 30", "DamageInspection.BatteryConnectors");
            Fields.Add("Text Field 31", "DamageInspection.Guards");
            Fields.Add("Text Field 32", "DamageInspection.SafetyDevices");
            Fields.Add("Text Field 33", "DamageInspection.PropaneTankLines");
            Fields.Add("Check Box 3", "Date");
            Fields.Add("Check Box 4", "Date");
            Fields.Add("Check Box 7", "Date");
            Fields.Add("Check Box 10", "Date");
            Fields.Add("Check Box 13", "Date");
            Fields.Add("Check Box 16", "Date");
            Fields.Add("Check Box 19", "Date");
            Fields.Add("Check Box 22", "Date");
            Fields.Add("Check Box 25", "Date");
            Fields.Add("Check Box 28", "Date");
            Fields.Add("Check Box 31", "Date");
            Fields.Add("Check Box 34", "Date");
            Fields.Add("Check Box 37", "Date");
            Fields.Add("Check Box 40", "Date");
            Fields.Add("Check Box 43", "Date");
            Fields.Add("Check Box 46", "Date");
            Fields.Add("Check Box 49", "Date");
            Fields.Add("Check Box 52", "Date");
            Fields.Add("Check Box 55", "Date");
            Fields.Add("Check Box 58", "Date");
            Fields.Add("Check Box 61", "Date");
            Fields.Add("Check Box 64", "Date");
            Fields.Add("Check Box 67", "Date");
            Fields.Add("Check Box 70", "Date");
            Fields.Add("Check Box 73", "Date");
            Fields.Add("Check Box 76", "Date");
            Fields.Add("Check Box 79", "Date");
            Fields.Add("Check Box 82", "Date");
            Fields.Add("Check Box 85", "Date");
            Fields.Add("Check Box 88", "Date");
            Fields.Add("Check Box 2", "Date");
            Fields.Add("Check Box 5", "Date");
            Fields.Add("Check Box 8", "Date");
            Fields.Add("Check Box 11", "Date");
            Fields.Add("Check Box 14", "Date");
            Fields.Add("Check Box 17", "Date");
            Fields.Add("Check Box 20", "Date");
            Fields.Add("Check Box 23", "Date");
            Fields.Add("Check Box 26", "Date");
            Fields.Add("Check Box 29", "Date");
            Fields.Add("Check Box 32", "Date");
            Fields.Add("Check Box 35", "Date");
            Fields.Add("Check Box 38", "Date");
            Fields.Add("Check Box 41", "Date");
            Fields.Add("Check Box 44", "Date");
            Fields.Add("Check Box 47", "Date");
            Fields.Add("Check Box 50", "Date");
            Fields.Add("Check Box 53", "Date");
            Fields.Add("Check Box 56", "Date");
            Fields.Add("Check Box 59", "Date");
            Fields.Add("Check Box 62", "Date");
            Fields.Add("Check Box 65", "Date");
            Fields.Add("Check Box 68", "Date");
            Fields.Add("Check Box 71", "Date");
            Fields.Add("Check Box 74", "Date");
            Fields.Add("Check Box 77", "Date");
            Fields.Add("Check Box 80", "Date");
            Fields.Add("Check Box 83", "Date");
            Fields.Add("Check Box 86", "Date");
            Fields.Add("Check Box 89", "Date");
            Fields.Add("Check Box 1", "Date");
            Fields.Add("Check Box 6", "Date");
            Fields.Add("Check Box 9", "Date");
            Fields.Add("Check Box 12", "Date");
            Fields.Add("Check Box 15", "Date");
            Fields.Add("Check Box 18", "Date");
            Fields.Add("Check Box 21", "Date");
            Fields.Add("Check Box 24", "Date");
            Fields.Add("Check Box 27", "Date");
            Fields.Add("Check Box 30", "Date");
            Fields.Add("Check Box 33", "Date");
            Fields.Add("Check Box 36", "Date");
            Fields.Add("Check Box 39", "Date");
            Fields.Add("Check Box 42", "Date");
            Fields.Add("Check Box 45", "Date");
            Fields.Add("Check Box 48", "Date");
            Fields.Add("Check Box 51", "Date");
            Fields.Add("Check Box 54", "Date");
            Fields.Add("Check Box 57", "Date");
            Fields.Add("Check Box 60", "Date");
            Fields.Add("Check Box 63", "Date");
            Fields.Add("Check Box 66", "Date");
            Fields.Add("Check Box 69", "Date");
            Fields.Add("Check Box 72", "Date");
            Fields.Add("Check Box 75", "Date");
            Fields.Add("Check Box 78", "Date");
            Fields.Add("Check Box 81", "Date");
            Fields.Add("Check Box 84", "Date");
            Fields.Add("Check Box 87", "Date");
            Fields.Add("Check Box 90", "Date");
        }
    }
}
